character_comparison/urls.py
from django.urls import path, re_path
from . import views

app_name = 'character_comparison'
urlpatterns = [
    path('', views.comparison_home, name='comparison_home'),
    re_path(r'search/?$', views.comparison_search, name='comparison_search'),
]

characters/urls.py
from django.urls import path

from characters import views

urlpatterns = [
    path('', views.character_home, name='character_home'),
    path('<str:name>/', views.character_detail, name='character_detail'),
]

character_comparison/forms.py
from django import forms

from characters.models import Character
from armor.models import EquipArmorSlot

class CharacterGearComparison(forms.Form):
    classes = forms.MultipleChoiceField(choices=Character.CHAR_CLASSES, required=False, widget=forms.CheckboxSelectMultiple())
    slots = forms.MultipleChoiceField(choices=EquipArmorSlot.EQUIP_SLOTS, required=False, widget=forms.CheckboxSelectMultiple())
    char_sets = forms.MultipleChoiceField(choices=Character.CHAR_SETS, required=False, widget=forms.CheckboxSelectMultiple())

    def render(self, *args, **kwargs):
        output = super(CharacterGearComparison, self).render(*args, **kwargs)
        return mark_safe(output.replace(u'<ul>', u'').replace(u'</ul>', u'').replace(u'<li>', '<p>').replace(u'</li>', u'</p>'))

character_comparison/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from armor.models import EquipArmorSlot, Armor
from characters.models import Character
from django.db.models import Q
from character_comparison.forms import CharacterGearComparison


# Create your views here.
def comparison_home(request):
    form = CharacterGearComparison(request.GET)
    eas = EquipArmorSlot.objects.all()

    if request.method == 'GET':
        if form.is_valid():
            eas = filter_data(form)
            paginator = Paginator(eas, 100)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

    return render(request, 'comparison_search.html', {'page_obj': page_obj, 'form': form, 'eas': eas})


def comparison_search(request):
    form = CharacterGearComparison(request.GET)
    if request.method == 'GET':
        if form.is_valid():
            eas = filter_data(form)
            return render(request, 'comparison_search.html', {'form': form, 'eas': eas})
    else:
        form = CharacterGearComparison()
    return render(request, 'comparison_view.html', {'form': form})


def filter_data(form):
    eas = EquipArmorSlot.objects.all()
    # get data from form
    data = form.cleaned_data
    classes = data.get('classes')
    slots = data.get('slots')
    char_sets = data.get('char_sets')
    char_set_query = []
    for sets in char_sets:
        lookup = Character.CHAR_SETS_LOOK_UP[sets]
        for c in lookup:
            if c not in char_set_query:
                char_set_query.append(c)

    if len(classes) > 0:
        eas = eas.filter(character__char_class__in=classes)
    if len(slots) > 0:
        eas = eas.filter(current_equip_slot__in=slots)
    if len(char_set_query) > 0:
        eas = eas.filter(character__char_class__in=char_set_query)
    if len(slots) == 1:
        eas = eas.order_by('armor__hp_points')
    else:
        eas = eas.order_by('armor__hp_points', 'character')
    return eas

character_comparison/templates/comparison_home.html
{% extends 'header_footer.html' %}

{% block content %}

{% if eas %}
<h1>Armor List by CHARACTERS</h1>
<li><a class='Search' href="{% url 'character_comparison:comparison_search' %}">Search</a></li>
<table border="1">
    <tr>
        <th>Character Name</th>
        <th>Class</th>
        <th>Armor Name</th>
        <th>HP</th>
        <th>Mana</th>
        <th>Equip Slot</th>
        <th>Aug1</th>
        <th>Aug2</th>
    </tr>
    {% for e in eas %}
    <tr>
        <td><a href={% url 'character_detail' name=e.character %}> {{ e.character }} </a></td>
        <td> {{ e.character.char_class }}</td>
        <td> {{ e.armor }}</td>
        <td> {{ e.armor.hp_points }}</td>
        <td>{{ e.armor.mana_points }}</td>
        <td>{{ e.slot_verbose }}</td>
        <td>{{ e.aug1 }}</td>
        <td>{{ e.aug2 }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}

character_comparison/templates/comparison_search.html
{% extends 'comparison_view.html' %}

{% block character_detail %}
<h1>Armor List by CLASS/SLOT</h1>
<h2>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</h2>
<div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            <a href="?page=1">First</a>

            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
        </span>
</div>
<table border="1">
    <th>Character Name</th>
    <th>Class</th>
    <th>Armor Name</th>
    <th>HP</th>
    <th>Mana</th>
    <th>Equip Slot</th>
    <th>Aug1</th>
    <th>Aug2</th>
    {% for e in page_obj %}
    <tr>
        <td><a href={% url 'character_detail' name=e.character %}> {{ e.character }} </a></td>
        <td> {{ e.character.char_class }}</td>
        <td> {{ e.armor }}</td>
        <td> {{ e.armor.hp_points }}</td>
        <td> {{ e.armor.mana_points }}</td>
        <td> {{ e.slot_verbose }}</td>
        <td> {{ e.aug1 }}</td>
        <td> {{ e.aug2 }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

character_comparison/templates/comparison_view.html
{% extends 'header_footer.html' %}

{% block content %}

    <form method="get">
        {{ form.non_field_errors }}
        {{ form.source.errors }}
        {{ form.source }}
        <table border="1">
            <tr>
                <th> {{ form.classes.label_tag }} </th>
                <td>
                    {% for value, text in form.classes.field.choices %}
                    <label for="id_classes_{{ forloop.counter0 }}"><input type="checkbox" name="classes" value="{{ value }}" id="id_classes_{ forloop.counter0 }}">{{ text }}</label>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th> {{ form.slots.label_tag }} </th>
                <td>
                    {% for value, text in form.slots.field.choices %}
                    <label for="id_slots_{{ forloop.counter0 }}"><input type="checkbox" name="slots" value="{{ value }}" id="id_slots_{{ forloop.counter0 }}">{{ text }}</label>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th> {{ form.char_sets.label_tag }} </th>
                <td>
                    {% for value, text in form.char_sets.field.choices %}
                    <label for="id_char_sets_{{ forloop.counter0 }}">
                        <input type="checkbox" name="char_sets" value="{{ value }}" id="id_char_sets_{{ forloop.counter0 }}">{{ value }}</label>
                    {% endfor %}
                </td>
            </tr>
        </table>
        <input type='submit' value='Filter'>
    </form>

{% block character_detail %}
{% endblock %}

{% endblock %}